---
apiVersion: v1
kind: Namespace
metadata:
  name: california-voter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: california-voter
  name: california-voter-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: california-voter-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: california-voter-app
    spec:
      containers:
      - image: nushan23/voterapi:main
        imagePullPolicy: Always
        name: california-voter-app
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  namespace: california-voter
  name: california-voter-service
spec:
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: california-voter-app
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: california-voter
  name: management-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: management-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: management-app
    spec:
      containers:
      - image: nushan23/managementapi:main
        imagePullPolicy: Always
        name: management-app
        ports:
        - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  namespace: california-voter
  name: management-service
spec:
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: management-app
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: california-voter
  name: monitoring-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: monitoring-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monitoring-app
    spec:
      containers:
      - image: nushan23/monitoringapi:main
        imagePullPolicy: Always
        name: monitoring-app
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  namespace: california-voter
  name: monitoring-service
spec:
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: monitoring-app
  type: LoadBalancer
status:
  loadBalancer: {}